"""Backward-pass NaN in a feed-forward neural network training step.

A two-hidden-layer MLP is trained with an RMSE loss,
`sqrt(mean((pred - y)^2))`. The trap: the derivative of RMSE is
`(pred - y) / (n * rmse)` — and on a batch the network fits *exactly*
(here: distillation against targets produced by the same network), the
loss is 0 and every gradient is `0 / 0 = NaN`. One such batch silently
poisons all parameters; training "diverges" with no error message.

The forward pass is completely healthy, so jax_debug_nans-style tools
point at the opaque backward computation. find_grad_nan_source blames the
backward `div` and its call stack leads to the `jnp.sqrt` in rmse_loss —
the line to fix (use MSE, or `sqrt(mse + eps)`).
"""

import jax
import jax.numpy as jnp

from jax_nan_debugger import find_grad_nan_source


def init_mlp(key, sizes):
    """Initialize [(w, b), ...] for a feed-forward net with given layer sizes."""
    params = []
    for n_in, n_out, k in zip(sizes[:-1], sizes[1:], jax.random.split(key, len(sizes) - 1)):
        params.append(
            (jax.random.normal(k, (n_in, n_out)) / jnp.sqrt(n_in), jnp.zeros(n_out))
        )
    return params


def mlp(params, x):
    for w, b in params[:-1]:
        x = jnp.tanh(x @ w + b)
    w, b = params[-1]
    return x @ w + b


def rmse_loss(params, x, y):
    pred = mlp(params, x)
    return jnp.sqrt(jnp.mean((pred - y) ** 2))


def mse_loss(params, x, y):
    pred = mlp(params, x)
    return jnp.mean((pred - y) ** 2)


def main():
    key = jax.random.PRNGKey(42)
    params = init_mlp(key, sizes=[8, 16, 16, 1])
    x = jax.random.normal(jax.random.key(1), (32, 8))

    # A perfectly-fit batch: targets generated by the network itself.
    y_exact = mlp(params, x)
    # A normal batch: independent targets.
    y_noisy = y_exact + 0.1 * jax.random.normal(jax.random.key(2), y_exact.shape)

    loss, grads = jax.value_and_grad(rmse_loss)(params, x, y_exact)
    w1_grad = grads[0][0]
    print(f"loss = {loss}  (finite!)   first-layer grad w: {w1_grad.ravel()[:3]} ...\n")

    print("=== RMSE loss, perfectly-fit batch ===")
    print(find_grad_nan_source(rmse_loss, params, x, y_exact))

    print("\n=== RMSE loss, normal batch ===")
    print(find_grad_nan_source(rmse_loss, params, x, y_noisy))

    print("\n=== MSE loss, perfectly-fit batch (the fix) ===")
    print(find_grad_nan_source(mse_loss, params, x, y_exact))


if __name__ == "__main__":
    main()
